package com.bankofshanghai.drools;  
   
import com.bankofshanghai.pojo.BankData;  
import com.bankofshanghai.mypojo.StatisticsData; 

rule "1"  
    when
        $data : BankData(touserCredit< 0 && money>=1000.00)
    then  
        $data.setSafeLevel($data.getSafeLevel()+45); 
end  
   
rule "2"  
    when
        $data : BankData(money>=1000.00)
        $sdata : StatisticsData(commonFromPlace!=$data.fromplace)
    then  
        $data.setSafeLevel($data.getSafeLevel()+30);  
end  

rule "3"  
    when
        $data : BankData(money>=1000.00)
        $sData : StatisticsData(isNewUser==true)
    then  
        $data.setSafeLevel($data.getSafeLevel()+15);  
end 

rule "4"  
    when
        $data : BankData()
        $sData : StatisticsData(isNewUser==true && moneyOfDay>=5000.00)
    then  
        $data.setSafeLevel($data.getSafeLevel()+15);
end  

rule "5"  
    when
        $data : BankData()
        $sData : StatisticsData(moneyWithinTime>= 5000.00)
    then  
        $data.setSafeLevel($data.getSafeLevel()+30);
end 

