package com.bankofshanghai.drools;  
   
import com.bankofshanghai.pojo.BankData;  
import com.bankofshanghai.mypojo.StatisticsData;  
   
rule "999"  
	salience 999
    when
        $data : BankData()
    then  
        $data.setSafeLevel(0);  
end  
   
rule "1"  
	salience 1
    when
        $data : BankData()
        $sData : StatisticsData(commonFromPlace!=$data.fromplace)
    then  
        $data.setSafeLevel(3);  
end  

rule "2"  
	salience 2
    when
        $data : BankData()
        $sData : StatisticsData(dataNumbersFromTime>=3)
    then  
        $data.setSafeLevel(2);  
end  
