package com.bankofshanghai.drools;  
   
import com.bankofshanghai.pojo.BankData;  
import com.bankofshanghai.mypojo.StatisticsData; 
import com.bankofshanghai.mypojo.CheckPass; 

rule "1"  
    when
        $factor : RuleFactor(data.money>=500&data.fromplace!=sData.commonFromPlace)
    then  
        $factor.data.setSafeLevel($factor.data.getSafeLevel()+30)
end  

rule "2"  sbuilder.append('\n');
    when
        $data : BankData(touserCredit< 0)
        $pass : CheckPass()
    then  
        $pass.setPass(true);
end  

